# fly.toml app configuration file generated for gpt-hero on 2024-06-19T21:11:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gpt-hero'
primary_region = 'dfw'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-8x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
